### ISSUE TITLE
Any sample to help us to absolutely config it properly without any doubt? 

### ISSUE THREAD

**Issue by TonyTangAndroid** [akaita/RxJava2Debug#1]
I have tried to configure this library in my project, but it did not give extra information for me. With or without the RxJava2Debug applied, it gives same obscure information. a [sample repository](https://github.com/TonyTangAndroid/RxJava2DebugIssueDemo) has been created to reproduce this issue.

Is it because I did not config the Rxjava2Debug incorrectly?
Or is it because I am not understanding the Rxjava2Debug function correctly?
Or is it because there might be a potential enhancement that needs to be done to achieve such purpose?

Any help, hints or guidance will be appreciated.

Without Rxjava2Debug applied, it prints out the following obscure information:

```java
W: java.lang.NullPointerException: Callable returned null
W:     at io.reactivex.internal.functions.ObjectHelper.requireNonNull(ObjectHelper.java:39)
W:     at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:42)
W:     at io.reactivex.Observable.subscribe(Observable.java:10842)
W:     at io.reactivex.Observable.subscribe(Observable.java:10828)
W:     at io.reactivex.Observable.subscribe(Observable.java:10788)
W:     at com.github.tonytangandroid.rxjava2debugdemo.MainActivity.onCreate(MainActivity.java:23)
W:     at android.app.Activity.performCreate(Activity.java:6682)
W:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
W:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
W:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
W:     at android.app.ActivityThread.-wrap12(ActivityThread.java)
W:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
W:     at android.os.Handler.dispatchMessage(Handler.java:102)
W:     at android.os.Looper.loop(Looper.java:154)
W:     at android.app.ActivityThread.main(ActivityThread.java:6121)
W:     at java.lang.reflect.Method.invoke(Native Method)
W:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
W:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

 
With Rxjava2Debug applied it still prints out the same obscure information. It is suppose to locate the root problem, which roots from `NullRepo.java` at [here](https://github.com/TonyTangAndroid/RxJava2DebugIssueDemo/blob/master/app/src/main/java/com/github/tonytangandroid/rxjava2debugdemo/NullRepo.java#L12):

```java
W: java.lang.NullPointerException: Callable returned null
W:     at io.reactivex.internal.functions.ObjectHelper.requireNonNull(ObjectHelper.java:39)
W:     at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:42)
W:     at io.reactivex.Observable.subscribe(Observable.java:10842)
W:     at io.reactivex.Observable.subscribe(Observable.java:10828)
W:     at io.reactivex.Observable.subscribe(Observable.java:10788)
W:     at com.github.tonytangandroid.rxjava2debugdemo.MainActivity.onCreate(MainActivity.java:23)
W:     at android.app.Activity.performCreate(Activity.java:6682)
W:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
W:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
W:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
W:     at android.app.ActivityThread.-wrap12(ActivityThread.java)
W:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
W:     at android.os.Handler.dispatchMessage(Handler.java:102)
W:     at android.os.Looper.loop(Looper.java:154)
W:     at android.app.ActivityThread.main(ActivityThread.java:6121)
W:     at java.lang.reflect.Method.invoke(Native Method)
W:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
W:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by akaita** [comment]
It looks like you have it disabled: `https://github.com/TonyTangAndroid/RxJava2DebugIssueDemo/blob/master/app/src/main/java/com/github/tonytangandroid/rxjava2debugdemo/App.java`

```
//        RxJava2Debug.enableRxJava2AssemblyTracking();
```

Obvious question: did you try uncommenting it?

**Comment by TonyTangAndroid** [comment]
Yes. I have tried to disable or enable it in both use case hoping to generate the different stack. But it is turned out to be the same.

**Comment by TonyTangAndroid** [comment]
Hold on. I think I know the reason.

**Comment by TonyTangAndroid** [comment]
Nope. It still does not work as expected. Previously, I made a silly mistake. I did not registered the `Application` in `AndroidManifest.xml`.

I have just registered it and enabled it and I still get the same error.

**Comment by akaita** [comment]
Ok. Now I read the stacktrace you posted.

Try using this: `RxJava2Debug.enableRxJava2AssemblyTracking(new String[]{"com.github.tonytangandroid"});`

**Comment by TonyTangAndroid** [comment]
I have just tried it. Still no luck here.

**Comment by akaita** [comment]
Oh, you are consuming the error:
```
 new Consumer<Throwable>() {
            @Override
            public void accept(@NonNull Throwable throwable) throws Exception {
                throwable.printStackTrace();
                tvResult.setText(throwable.getMessage());
            }
        },
```

If you already consume the error, you already have the necessary information to fix the issue; the lib would only show you information you already know about. 
The lib will improve the StackTrace of Unhandled exceptions.

What additional info did you expect to receive?

**Comment by TonyTangAndroid** [comment]
Aha, it is. After the error consumer has been removed AND removed the `new String[]{"com.github.tonytangandroid"}` from `RxJava2Debug.enableRxJava2AssemblyTracking(new String[]{"com.github.tonytangandroid"});`, it works!

Please be noted that I have to remove `new String[]{"com.github.tonytangandroid"}` to see the expected stack information.

**Comment by TonyTangAndroid** [comment]
Before your explanation about error Consumer, I had expected in a wrong way that, even I have consumer to address the throwable, but as long as I print the stack trace of the throwable, it would still show the root cause of the error. This would be more helpful.

And in my project, I have to add an error consumer to address the unhandled case globally. However, this makes me really difficult to track down issues like because the stack trace does not provide any help. And that's the reason why I come across to this repository. 

Assume that I still have to consume the error in my subscriber, is there any other way  to still see the root cause of any exception as long as the stack trace is printed out?

**Comment by akaita** [comment]
I just found why the filtering wasn't working. The filtering won't work when you user UI Thread for all tasks. I'll issue a fix this weekend.

I didn't think about your use case. I can easily modify the lib to offer you something like `RxJava2Debug.getEnhancedStackTrace(Throwable t)` 🤔 
Yeah, this weekend will also be enough for that 👍

**Comment by TonyTangAndroid** [comment]
Awesome! Thank you very much for all your time, patience and guidance.

**Comment by akaita** [comment]
Try out `1.2.0` 👍

**Comment by TonyTangAndroid** [comment]
It works!!! To be more specific, it work exactly what I have been hoping for. From now on, I no longer have to follow the observable stream to hunt the myth of  "Callable returned null" or any other error info. This is too awesome to be true.
